### ISSUE TITLE
Room name containing my own `displayName`

### ISSUE THREAD

**Issue by louisgrasset** [mautrix/twitter#29]
It sounds like DM with a signle person a created with a name with that pattern:
`{self:displayName} {recipient:displayName} (Twitter)`

Current configuration is the original one: `{displayName} (Twitter)`. 

May it be possible to filter `displayName` of my own name?

**Comment by scarpentier** [comment]
Have you enabled [Double puppeting](https://docs.mau.fi/bridges/general/double-puppeting.html#double-puppeting) for your account on your bridge?

**Comment by wolveix** [comment]
For anyone stumbling across this, if you know you have double puppeting enabled/configured and this is only happening in group chats, you need to set the following:

```
matrix_mautrix_twitter_configuration_extension_yaml: |
  bridge:
    backfill:
      # Whether or not the Twitter users of logged in Matrix users should be
      # invited to private chats when backfilling history from Twitter. This is
      # usually needed to prevent rate limits and to allow timestamp massaging.
      invite_own_puppet: false
```
